aws_region = "us-east-1"
project_name = "strapi"
image_uri = "public.ecr.aws/docker/library/nginx:latest"
execution_role_arn = "arn:aws:iam::811738710312:role/ecs_fargate_taskRole"
codedeploy_role_arn = "arn:aws:iam::811738710312:role/codedeploy_role"