name: Terraform Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: terraform
    
    env:
      TF_VAR_aws_region: us-east-1
      TF_VAR_project_name: strapi
      TF_VAR_execution_role_arn: ${{ secrets.ECS_EXECUTION_ROLE_ARN }}
      TF_VAR_codedeploy_role_arn: ${{ secrets.CODEDEPLOY_ROLE_ARN }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan 

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve